version: '3'
services:
  app:
    build: ./client
    ports:
      - 80:80
    hostname: app
    links:
      - flask
  flask:
    build: ./api
    hostname: flask
    links:
      - mongodb
  mongodb:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db
    container_name: mongodb
volumes:
  dbdata6: