version: '3'
services:
  app:
    image: revelate123/app
    ports:
      - 80:80
    container_name: app
    links:
      - flask
  flask:
    image: revelate123/flask
    container_name: flask
    links:
      - mongodb
  mongodb:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db
    container_name: mongodb
volumes:
  dbdata6: