version: '3'
services:
  app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    container_name: app
    links:
      - flask
  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: flask
    links:
      - mongodb
  mongodb:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db
    container_name: mongodb
volumes:
  dbdata6: