name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./client
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/client:latest
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask:latest
  deploy:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        
        - name: Generate deployment package
          run: zip -r deploy.zip ./dockercompose -x '*.git*'

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: "ap-southeast-2"

        - name: Upload package to S3 bucket
          run: aws s3 cp deploy.zip s3://elasticbeanstalk-ap-southeast-2-058264415051/seek2/

        - name: Create new ElasticBeanstalk Application Version
          run: |
            aws elasticbeanstalk create-application-version \
            --application-name seek2 \
            --source-bundle S3Bucket="s3://elasticbeanstalk-ap-southeast-2-058264415051/seek2/", S3Key="deploy.zip" \
            --version-label "ver-${{ github.sha }}" \
            --description "commit-sha-${{ github.sha }}"

        - name: Deploy new ElasticBeanstalk Application Version
          run: aws elasticbeanstalk update-environment --environment-name seek2 --version-label "ver-${{ github.sha }}"





        
          
